stages:
  - test
  - staging
  - staging-fresh
#   - production

test:
  stage: test
  script:
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - php artisan migrate:fresh --seed
    - vendor/bin/phpunit
#   only:
#     - branches
#   except:
#     - master
  tags:
    - test

staging:
  stage: staging
  script:
    - cd /home/gitlab-runner/www/larabase/
    - sudo su www-data -s /bin/bash
    - git pull http://$GITUSER:$GITPASSWORD@srv.nazrol.tech/internal/laravel-base/
    - composer install
    - php artisan config:clear
    - php artisan view:clear
    - php artisan cache:clear
    - php artisan migrate
  environment:
    name: larabase
    url: http://larabase.nazrol.tech
  only:
    - master
  tags:
    - staging
    
staging-fresh:
  stage: staging
  script:
    - cd /home/gitlab-runner/www/larabase/
    - sudo su www-data -s /bin/bash
    - git pull http://$GITUSER:$GITPASSWORD@srv.nazrol.tech/internal/laravel-base/
    - composer install
    - php artisan config:clear
    - php artisan view:clear
    - php artisan cache:clear
    - php artisan migrate:fresh --seed
  environment:
    name: larabase
    url: http://larabase.nazrol.tech
  when: manual
  only:
    - master
  tags:
    - staging

# production:
#   stage: production
#   script:
#     - cd /home/nt/live/frontend
#     - sudo git pull http://$GIT_USER:$GIT_PASSWORD@runner02.nazrol.tech/root/frontend.git
#     - sudo chown www-data.www-data -R *
#     - sudo service nginx restart
#   environment:
#     name: production
#     url: http://frontend.live.net
#   when: manual
#   only:
#     - master
#   tags:
